implemented login and pw change of storage.go
Glorfischi/ASL pull request #10
Opened 2019-11-13 15:03 UTC by hxenia

isch irgendöbis bruchbar?....

2019-11-13 15:37 UTC, bimmlerd requested changes

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +	row := s.db.QueryRowContext(ctx, `SELECT uid FROM users WHERE uid=? AND pwn=?`, userID, pwHash)
`pwn` to `pwd`

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +	row = s.db.QueryRowContext(ctx, `UPDATE users SET pwn = ? WHERE uid=?`, pwHash, userID)
`pwn` to `pwd`

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +	pwHash := h.Sum([]byte(password))
https://play.golang.org/p/dPr9lt1uIS seems to this a bit differently

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +	pwHash := h.Sum([]byte(password))
https://play.golang.org/p/dPr9lt1uIS hashes a bit differently

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +	u := dbUser{}
I don't think you need to scan all of the dbUser, I think just `SELECT`ing the `uid` should be enough

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +		}
possibly add an `else` here where you explicitly log that no user was found

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +	row = s.db.QueryRowContext(ctx, `UPDATE users SET pwn = ? WHERE uid=?`, pwHash, userID)
Also, I think this should be `ExecContext` https://golang.org/pkg/database/sql/#DB.ExecContext since we don't expect results

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +	err = row.Scan()
As a result, you'll not get rows back, and can instead directly use the error returned

2019-11-13 15:37 UTC, bimmlerd commented on IdP/storage.go
> +		}
Possibly add a explicit failed login attempt log.

2019-11-14 13:57 UTC, glrf approved these changes

2019-11-14 15:30 UTC, merged